### ISSUE TITLE
Milestone 2.0

### ISSUE THREAD

**Issue by pnicolli** [PloneGov-IT/redturtle.agidtheme#22]
L'idea di partire con lo sviluppo di una versione 2.0 nasce dalla necessità di sostituire FontAwesome 4 con la nuova versione 5, e i lavori in quel senso sono ormai terminati.

Se rilasciamo una nuova major con eventuali breaking changes, che cos'altro possiamo inserire in quel rilascio? Partirei dall'attingere dalle issue attuali, per esempio la questione dei bundle di risorse, ma possiamo aggiungere altre eventuali idee.

**Comment by nzambello** [comment]
Oltre a quanto detto da te, sicuramente guarderei la #21, mi sembra piuttosto importante.
Dopodiché, importerei Titillium in locale (ora su connessioni lente arriva tardi).

**Comment by nzambello** [comment]
Allo stato attuale, bisogna procedere e penso che abbiamo chiuso le cose più importanti.
Eseguo gli ultimi test sulla #20 e poi procedo a mergiare la #20 e successivamente la #19.
