### ISSUE TITLE
Header: find a smarter way for social links

### ISSUE THREAD

**Issue by nzambello** [PloneGov-IT/redturtle.agidtheme#3]
@pnicolli said: I used to do this with portal_actions, but I guess we should move away from ZMI from now on, so something related to the plone registry could be better, as usual.

@cekk said: I upvoted this issue because we NEED this in another site. Obviously: don't show the viewlet if there aren't social set

**Comment by nzambello** [comment]
@cekk I think it's fixed in #8, isn't it?

**Comment by cekk** [comment]
yes, let's close this issue
